/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author janja
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        itemKreirajIzn = new javax.swing.JMenuItem();
        itemPrikaziIzn = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemKreirajZaposleni = new javax.swing.JMenuItem();
        itemPrikaziZaposleni = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemKreirajSkijasa = new javax.swing.JMenuItem();
        itemPrikaziSkijas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Zdravo, ");

        jMenu6.setText("Iznajmljivanje");

        itemKreirajIzn.setText("Kreiraj");
        jMenu6.add(itemKreirajIzn);

        itemPrikaziIzn.setText("Prikazi");
        jMenu6.add(itemPrikaziIzn);

        jMenuBar1.add(jMenu6);

        jMenu1.setText("Zaposleni");

        itemKreirajZaposleni.setText("Kreiraj");
        itemKreirajZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKreirajZaposleniActionPerformed(evt);
            }
        });
        jMenu1.add(itemKreirajZaposleni);

        itemPrikaziZaposleni.setText("Prikazi");
        jMenu1.add(itemPrikaziZaposleni);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Skijaš");

        itemKreirajSkijasa.setText("Kreiraj");
        jMenu2.add(itemKreirajSkijasa);

        itemPrikaziSkijas.setText("Prikazi");
        itemPrikaziSkijas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrikaziSkijasActionPerformed(evt);
            }
        });
        jMenu2.add(itemPrikaziSkijas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ski oprema");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Nivo skijanja");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Termin");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblUlogovani)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKreirajZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKreirajZaposleniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemKreirajZaposleniActionPerformed

    private void itemPrikaziSkijasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrikaziSkijasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPrikaziSkijasActionPerformed

    public JLabel getLblUlogovani() {
        return lblUlogovani;
    }

    public void prikaziSkijasAddActionListener(ActionListener actionListener){
        itemPrikaziSkijas.addActionListener(actionListener);
    }
    
    public void prikaziIznAddActionListener(ActionListener actionListener){
        itemPrikaziIzn.addActionListener(actionListener);
    }
    
    public void kreirajSkijasaAddActionListener(ActionListener actionListener){
        itemKreirajSkijasa.addActionListener(actionListener);
    }
    
    public void prikaziZaposleniAddActionListener(ActionListener actionListener){
        itemPrikaziZaposleni.addActionListener(actionListener);
    }
    
    public void kreirajZaposleniAddActionListener(ActionListener actionListener){
        itemKreirajZaposleni.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemKreirajIzn;
    private javax.swing.JMenuItem itemKreirajSkijasa;
    private javax.swing.JMenuItem itemKreirajZaposleni;
    private javax.swing.JMenuItem itemPrikaziIzn;
    private javax.swing.JMenuItem itemPrikaziSkijas;
    private javax.swing.JMenuItem itemPrikaziZaposleni;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUlogovani;
    // End of variables declaration//GEN-END:variables
}
